# Dockerfile.multistage
# Stage 1: Build
FROM node:14 AS build

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY ./app .

# Stage 2: Production
FROM gcr.io/distroless/nodejs:14

WORKDIR /usr/src/app

COPY --from=build /usr/src/app .

CMD ["app/index.js"]
